timeout: 1800s
steps:
  - name: node:12.13.0
    entrypoint: yarn
    args: ['install']
  - name: node:12.13.0
    entrypoint: yarn
    args: ['tsc']
  - name: node:12.13.0
    entrypoint: yarn
    args: ['build']
  - name: gcr.io/cloud-builders/gcloud
    args: ['functions', 'deploy', 'etl-cheaters', '--source=functions/etl-cheaters', '--max-instances=32', '--memory=128MB', '--timeout=90', '--trigger-http', '--entry-point=default', '--runtime=nodejs12', '--region=us-east1' ]
