timeout: 1800s
steps:
    - name: node:12.13.0
      entrypoint: yarn
      args: ['install']
    - name: node:12.13.0
      entrypoint: yarn
      args: ['gcp:tsc']
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=MONGO_HOST > build/.env.MONGO_HOST' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=MONGO_USER > build/.env.MONGO_USER' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=MONGO_PASS > build/.env.MONGO_PASS' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=JWT_SECRET > build/.env.JWT_SECRET' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=DISCORD_TOKEN > build/.env.DISCORD_TOKEN' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=GMAIL_ADDRESS > build/.env.GMAIL_ADDRESS' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=GMAIL_PASSWORD > build/.env.GMAIL_PASSWORD' ]
    - name: node:12.13.0
      entrypoint: yarn
      args: ['gcp:build']
    - name: gcr.io/cloud-builders/gcloud
      args: ['app', 'deploy', 'apps/api',    '--version=production']
    - name: gcr.io/cloud-builders/gcloud
      args: ['app', 'deploy', 'apps/web-ui', '--version=production']
    - name: gcr.io/cloud-builders/gcloud
      args: ['functions', 'deploy', 'render-chart',     '--source=services/render-chart',       '--max-instances=12', '--memory=128MB', '--timeout=60',  '--trigger-http', '--entry-point=default', '--runtime=nodejs12', '--region=us-east1']
    - name: gcr.io/cloud-builders/gcloud
      args: ['functions', 'deploy', 'render-html',      '--source=services/render-html',        '--max-instances=12', '--memory=512MB', '--timeout=60',  '--trigger-http', '--entry-point=default', '--runtime=nodejs12', '--region=us-east1']
    - name: gcr.io/cloud-builders/gcloud
      args: ['functions', 'deploy', 'scrape-scheduler', '--source=services/scrape-scheduler',   '--max-instances=2',  '--memory=128MB', '--timeout=60', '--trigger-http', '--entry-point=default', '--runtime=nodejs12', '--region=us-east1', '--env-vars-file=services/scrape-scheduler/.env.yaml']
    - name: gcr.io/cloud-builders/gcloud
      args: ['functions', 'deploy', 'scrape-worker-cod', '--source=services/scrape-worker-cod', '--max-instances=12', '--memory=128MB', '--timeout=540', '--trigger-http', '--entry-point=default', '--runtime=nodejs12', '--region=us-east1', '--env-vars-file=services/scrape-worker-cod/.env.yaml']
    - name: gcr.io/cloud-builders/gcloud
      args: ['app', 'deploy', 'dispatch.yaml', '--version=production']
