timeout: 1800s
steps:
    - name: node:12.13.0
      entrypoint: yarn
      args: ['install']
    - name: node:12.13.0
      entrypoint: yarn
      args: ['gcp:tsc']
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=API_HOST > build/.env.API_HOST' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=JWT_SECRET > build/.env.JWT_SECRET' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=GMAIL_USER > build/.env.GMAIL_USER' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=GMAIL_PASS > build/.env.GMAIL_PASS' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=MONGO_HOST > build/.env.MONGO_HOST' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=MONGO_USER > build/.env.MONGO_USER' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=MONGO_PASS > build/.env.MONGO_PASS' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=PGSQL_USER > build/.env.PGSQL_USER' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=PGSQL_PASS > build/.env.PGSQL_PASS' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=PGSQL_PORT > build/.env.PGSQL_PORT' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=PGSQL_INSTANCE > build/.env.PGSQL_INSTANCE' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=PGSQL_SOCKETPATH > build/.env.PGSQL_SOCKETPATH' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=FAAS_ETL_COD_TTL  > build/.env.FAAS_ETL_COD_TTL' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=FAAS_ETL_COD_HOST > build/.env.FAAS_ETL_COD_HOST' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=FAAS_RENDER_HTML_HOST > build/.env.FAAS_RENDER_HTML_HOST' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=FAAS_RENDER_CHART_HOST > build/.env.FAAS_RENDER_CHART_HOST' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=DISCORD_CLIENT_TOKEN > build/.env.DISCORD_CLIENT_TOKEN' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=DISCORD_CHANNEL_NOTIFY_SYS > build/.env.DISCORD_CHANNEL_NOTIFY_SYS' ]
    - name: node:12.13.0
      entrypoint: yarn
      args: ['gcp:build']
    - name: gcr.io/cloud-builders/gcloud
      args: ['app', 'deploy', 'apps/api',    '--version=production']
    - name: gcr.io/cloud-builders/gcloud
      args: ['app', 'deploy', 'apps/web-ui', '--version=production']
    - name: gcr.io/cloud-builders/gcloud
      args: ['functions', 'deploy', 'render-chart',     '--source=services/render-chart',       '--max-instances=12', '--memory=128MB', '--timeout=60',  '--trigger-http', '--entry-point=default', '--runtime=nodejs12', '--region=us-east1']
    - name: gcr.io/cloud-builders/gcloud
      args: ['functions', 'deploy', 'render-html',      '--source=services/render-html',        '--max-instances=12', '--memory=512MB', '--timeout=60',  '--trigger-http', '--entry-point=default', '--runtime=nodejs12', '--region=us-east1']
    - name: gcr.io/cloud-builders/gcloud
      args: ['functions', 'deploy', 'etl-callofduty',   '--source=services/etl-callofduty',     '--max-instances=12', '--memory=128MB', '--timeout=540', '--trigger-http', '--entry-point=default', '--runtime=nodejs12', '--region=us-east1', '--env-vars-file=services/etl-callofduty/.env.yaml']
    - name: gcr.io/cloud-builders/gcloud
      args: ['app', 'deploy', 'dispatch.yaml', '--version=production']
