timeout: 1800s
steps:
    - name: node:12.13.0
      entrypoint: yarn
      args: ['install']
    - name: node:12.13.0
      entrypoint: yarn
      args: ['gcp:tsc']
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=MONGO_HOST > build/.env.MONGO_HOST' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=MONGO_USER > build/.env.MONGO_USER' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=MONGO_PASS > build/.env.MONGO_PASS' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=JWT_SECRET > build/.env.JWT_SECRET' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=DISCORD_TOKEN > build/.env.DISCORD_TOKEN' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=GMAIL_ADDRESS > build/.env.GMAIL_ADDRESS' ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', 'gcloud secrets versions access latest --secret=GMAIL_PASSWORD > build/.env.GMAIL_PASSWORD' ]
    - name: node:12.13.0
      entrypoint: yarn
      args: ['gcp:build']
    - name: gcr.io/cloud-builders/gcloud
      args: ['app', 'deploy', 'services/discord', '--version=production']
    - name: gcr.io/cloud-builders/gcloud
      args: ['app', 'deploy', 'services/img.chart', '--version=production']
    - name: gcr.io/cloud-builders/gcloud
      args: ['app', 'deploy', 'services/img.view', '--version=production']
    - name: gcr.io/cloud-builders/gcloud
      args: ['app', 'deploy', 'services/scrape', '--version=production']
    - name: gcr.io/cloud-builders/gcloud
      args: ['app', 'deploy', 'services/web-ui', '--version=production']
    - name: gcr.io/cloud-builders/gcloud
      args: ['app', 'deploy', 'dispatch.yaml', '--version=production']