timeout: 1800s
steps:
  - name: node:12.13.0
    entrypoint: yarn
    args: ['install']
  - name: node:12.13.0
    entrypoint: yarn
    args: ['tsc']
  - name: node:12.13.0
    entrypoint: yarn
    args: ['build']
  - name: gcr.io/cloud-builders/gcloud
    args: ['app', 'deploy', 'applications/api', '--version=production']
